import requests
import json

def test_all_models():
    # OmniRoute का लोकल चैट एंडपॉइंट
    url = "http://localhost:20128/v1/chat/completions"
    
    # जिन मॉडल्स को आप टेस्ट करना चाहते हैं
    models_to_test = [
        "cc/claude-opus-4-6",
        "gh/gpt-5",
        "gc/gemini-3.1-pro-preview",
        "gc/gemini-2.5-pro"
    ]
    
    # बिज़नेस फैंटेसी के लिए हाई-रीज़निंग प्रॉम्प्ट
    story_prompt = """
    Pocket FM के लिए 'The Silent Billionaire' जैसी एक शानदार Business Fantasy ऑडियो सीरीज़ का Episode 1 लिखें।
    भाषा: हिंदी (केवल देवनागरी लिपि में)।
    प्लॉट: हीरो एक बहुत ही गरीब और साधारण लड़का है जिसे हर कोई नीचा दिखाता है, लेकिन अचानक उसे पता चलता है कि वह दुनिया के सबसे बड़े और गुप्त बिज़नेस एम्पायर का असली वारिस है। 
    निर्देश: कहानी में बहुत गहरा सस्पेंस, हाई-रीज़निंग और ड्रामा होना चाहिए। श्रोताओं को हुक (Hook) करने वाले डायलॉग्स लिखें। एपिसोड लगभग 300-400 शब्दों का हो।
    """

    print("Starting Model Testing Process...")

    # आउटपुट फाइल बनाना
    with open("Story_Test_Results.md", "w", encoding="utf-8") as file:
        file.write("# OmniRoute Models - Story Generation Test\n\n")
        
        for model in models_to_test:
            print(f"\nRequesting story from model: {model}...")
            file.write(f"## [Generated by: {model}]\n\n")
            
            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": "You are an expert audio series scriptwriter."},
                    {"role": "user", "content": story_prompt}
                ],
                "max_tokens": 1500,
                "temperature": 0.7
            }
            
            try:
                # 3 मिनट का टाइमआउट ताकि अगर मॉडल स्लो हो तो रुके नहीं
                response = requests.post(url, json=payload, timeout=180)
                
                if response.status_code == 200:
                    data = response.json()
                    story = data['choices'][0]['message']['content']
                    file.write(story + "\n\n")
                    print(f"✅ Success: Story generated by {model}")
                else:
                    # अगर प्रोवाइडर कनेक्ट नहीं है या कोई 500 एरर आता है
                    error_msg = f"Error {response.status_code}: {response.text}"
                    file.write(f"> **इस मॉडल से कहानी जनरेट नहीं हो पाई।**\n> कारण: `{error_msg}`\n\n")
                    print(f"❌ Failed: {model} returned error {response.status_code}")
                    
            except Exception as e:
                file.write(f"> **सर्वर या कनेक्शन में रुकावट।**\n> कारण: `{str(e)}`\n\n")
                print(f"⚠️ Exception with {model}: {e}")
            
            file.write("---\n\n") # कहानियों के बीच लाइन खींचने के लिए

    print("\nAll testing completed. Results saved to Story_Test_Results.md")

if __name__ == "__main__":
    test_all_models()
    
